# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

# TODO: run zillib tests (needs PowerShell)
# TODO: run unit tests, dotnet test Zilf.sln (need to fix CRLF test issues)
# TODO: build custom Docker image instead of apt-get

image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - apt-get update -y && apt-get install -y zip
          - "dotnet msbuild -t:PackageAllRids -p:Configuration=Release Build.proj"
        artifacts:
          - Package/*/Packages/*